name: "CI: autotools: clang 6"

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Build
      run: |
        sudo apt update
        sudo apt install mm-common clang-6.0
        export CXX=clang++-6.0
        mkdir build
        cd build
        ../autogen.sh
        make
    - name: Test
      run: |
        cd build
        make check
    - name: Distcheck
      run: |
        cd build
        make distcheck
